CREATE TABLE `finantial_ct8` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nit` varchar(20) DEFAULT NULL,
  `check_digit` varchar(5) DEFAULT NULL,
  `entity_code` varchar(40) DEFAULT NULL,
  `period` varchar(45) DEFAULT NULL,
  `year` varchar(10) DEFAULT NULL,
  `type_register` varchar(5) DEFAULT NULL,
  `investment` varchar(30)  DEFAULT NULL,
  `regimen_type` varchar(30)  DEFAULT NULL,
  `investment_account`  varchar(20) DEFAULT NULL,
  `nit_emitter` varchar(45) DEFAULT NULL,
  `check_digit_two` varchar(5) DEFAULT NULL,
  `name_emitter` varchar(100) DEFAULT NULL,
  `quantity` varchar(20) DEFAULT NULL,
  `participation` varchar(20) DEFAULT NULL,
  `historical_cost` varchar(20) DEFAULT NULL,
  `value_books` varchar(20) DEFAULT NULL,
  `value_stock` varchar(20) DEFAULT NULL,
  `market_value` varchar(20) DEFAULT NULL,
  `valorization` varchar(20) DEFAULT NULL,
  `provision` varchar(20) DEFAULT NULL,
  `process_id` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
