CREATE TABLE `finantial_ct150` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nit` varchar(20) DEFAULT NULL,
  `check_digit` varchar(5) DEFAULT NULL,
  `entity_code` varchar(40) DEFAULT NULL,
  `period` varchar(45) DEFAULT NULL,
  `year` varchar(10) DEFAULT NULL,
  `type_register` varchar(5) DEFAULT NULL,
  `type_regimen` varchar(5) DEFAULT NULL,
  `type_recover` varchar(5) DEFAULT NULL,
  `number_recover` varchar(20)  DEFAULT NULL,
  `date_recover` varchar(20)  DEFAULT NULL,
  `value_recover`  varchar(30) DEFAULT NULL,
  `date_response`  varchar(30) DEFAULT NULL,
  `result`  varchar(30) DEFAULT NULL,
  `conditional_payment_date`  varchar(30) DEFAULT NULL,
  `conditional_payment_value`  varchar(30) DEFAULT NULL,
  `date_payment`  varchar(30) DEFAULT NULL,
  `value_payment`  varchar(30) DEFAULT NULL,
  `date_glossy` varchar(30) DEFAULT NULL,
  `value_glossy` varchar(30) DEFAULT NULL,
  `code_glossy` varchar(30) DEFAULT NULL,
  `name_glossy` varchar(120) DEFAULT NULL,
  `process_id` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
