INSERT INTO `process_order_types` VALUES 
(13,'registros lma','health','0','')
,(14,'estudios de suficiencia','health','0','')
,(18,'Reporte de Ingresos vs costos','finantial','1','Esta grafica representa los costos de las actividades versus los ingresos de la liquidación mensual de afiliados(LMA).')
,(20,'Reporte ingresos LMA','finantial','1','Ingresos LMA de hombres y mujeres')
,(21,'Frecuencia de uso','health','1','El indicador de frecuencia de uso examina las atenciones promedio por afiliado en un periodo de tiempo.   Se debe presentar por Zona de Riesgo (Normal, Dispersión y concentración)
	, Grupos quinquenales; agregado por GESTARSALUD; y desagregado por EPS Asoci')
,(22,'Extensión de uso','health','1','La extensión de uso expresa la proporción de usuarios que consultaron en el periodo de tiempo.  Se debe presentar por Zona de Riesgo (Normal, Dispersión y concentración)
	, Grupos quinquenales; agregado por GESTARSALUD; y desagregado por EPS Asociada.')
,(24,'estudio prima pura','health','0','')
,(28,'Costos de atención por diagnóstico','health','1','Reporte de costos de atención segun diagnóstico, presenta número de usuarios atendidos, costos de procedimientos, medicamentos e insumos para la atención de un diagnóstico o grupo de diagnósticos. Se puede generar  agregado por GESTARSALUD; desagregado po')
,(29,'Costo de procedimientos','health','1','Reporte de costos de uno o varios procedimientos, presenta número de usuarios atendidos y los costos de procedimientos.  Se puede generar  agregado por GESTARSALUD; desagregado por EPS Asociada; Consolidado por Zona de Riesgo (Normal, Dispersión y Concent')
,(30,'Intensidad de uso','health','1','La intensidad de uso indica el número de atenciones de cada tipo de servicio que recibe cada persona atendida.  Se puede generar por Zona de Riesgo (Normal, Dispersión y concentración)
	, Grupos quinquenales; agregado por GESTARSALUD; y desagregado por EPS ')
,(31,'Marcado de calidad ','health','0','Proceso de marcado de calidad')
,(38,'Perfil Epidemiológico','health','1','<p>Reporte de las primeras diez causas de morbilidad atendida en la población de afiliados. Se puede generar por Zona de Riesgo (Normal, Dispersión y concentración)
	, Grupos quinquenales; agregado por GESTARSALUD; y desagregado por EPS Asociada.</p><p>Los diagnósticos clasificados como “otros” corresponden a otras causas de atención que no hacen parte de las primeras diez causas de morbilidad. Las agrupaciones diagnósticas clasificadas como “Rs y Zs” corresponde a los diagnósticos relacionados como “Factores que influyen en el estado de salud y contacto con los servicios de salud (Z00-Z99)” y “Síntomas, signos y hallazgos anormales clínicos y de laboratorio, no clasificados en otra parte (R00-R99)”.</p>')
,(45,'Reporte por ámbito','health','1','Reporte que presenta los costos de atenciones según ámbitos de atención. Se puede generar por Zona de Riesgo (Normal, Dispersión y concentración)
	, Grupos quinquenales; agregado por GESTARSALUD; y desagregado por EPS Asociada. ')
,(46,'Reporte por modalidad','health','1','Reporte que presenta los costos de atenciones según modalidades de contratación. Se puede generar por Zona de Riesgo (Normal, Dispersión y concentración)
	, Grupos quinquenales; agregado por GESTARSALUD; y desagregado por EPS Asociada. ')