# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    node_auth_helper:
        class: AppBundle\Security\Authentication\Node\AuthHelper
        arguments: ["@circle.restclient","%ahelper_host%"]

    ldap_user_provider:
        class: AppBundle\Security\User\LdapUserProvider
        arguments: ["@doctrine.orm.entity_manager","@node_auth_helper"]

    ldap.security.authentication.provider:
        class:  AppBundle\Security\Authentication\Provider\LdapAuthenticationProvider
        arguments: ['@ldap_user_provider','default',"@node_auth_helper","@doctrine.orm.entity_manager","@security.encoder_factory"]

    ldap.security.authentication.listener:
        class:  AppBundle\Security\Firewall\LdapListener
        parent: security.authentication.listener.abstract
        abstract: true

    data_table:
        class:  AppBundle\Services\Datatable
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    log_activity_manager:
        class:  AppBundle\Services\LogActivityManager
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]

    report_validator:
        class:  AppBundle\Services\ReportValidator
        arguments: ["@doctrine.orm.entity_manager","@service_container"]
    
    excelHelper:
        class:  AppBundle\Services\ExcelHelper

